// src/components/layout/Footer.tsx
import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, Mail, Phone, MapPin, ExternalLink } from 'lucide-react';

// Social icon SVGs (lucide-react doesn't include brand icons)
const LinkedinIcon = ({ size = 14 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor">
    <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/>
    <rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/>
  </svg>
);

const FacebookIcon = ({ size = 14 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor">
    <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/>
  </svg>
);

const GithubIcon = ({ size = 14 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor">
    <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/>
  </svg>
);

const FOOTER_LINKS = {
  Services: [
    { label: 'Custom Software', href: '/services/custom-software-development' },
    { label: 'Web Applications', href: '/services/web-application-development' },
    { label: 'Mobile Apps', href: '/services/mobile-app-development' },
    { label: 'AI & Machine Learning', href: '/services/ai-machine-learning' },
    { label: 'Cloud & DevOps', href: '/services/cloud-solutions-devops' },
    { label: 'UI/UX Design', href: '/services/ui-ux-design' },
  ],
  Solutions: [
    { label: 'PayFlow — FinTech', href: '/solutions/payflow' },
    { label: 'FraudShield AI', href: '/solutions/fraudshield' },
    { label: 'FieldOps', href: '/solutions/fieldops' },
    { label: 'ClaimWise', href: '/solutions/claimwise' },
    { label: 'AuthGate', href: '/solutions/authgate' },
    { label: 'View all 11 products →', href: '/solutions' },
  ],
  Company: [
    { label: 'About Us', href: '/about' },
    { label: 'Case Studies', href: '/case-studies' },
    { label: 'Blog / Insights', href: '/blog' },
    { label: 'Hire Developers', href: '/hire-developers' },
    { label: 'Careers', href: '/careers' },
    { label: 'FAQ', href: '/faq' },
  ],
  Tools: [
    { label: 'AI Project Estimator', href: '/tools/project-estimator' },
    { label: 'Compare Us', href: '/compare' },
    { label: 'Contact', href: '/contact' },
    { label: 'Privacy Policy', href: '/privacy-policy' },
    { label: 'Terms of Service', href: '/terms' },
  ],
};

const TECH_BADGES = ['Angular', 'React', 'Next.js', 'Flutter', '.NET', 'Python', 'AWS', 'Docker'];

export function Footer() {
  return (
    <footer style={{ background: '#080C18', borderTop: '1px solid var(--border)' }}>
      {/* Main footer */}
      <div className="container" style={{ padding: '80px 32px 64px' }}>
        <div className="grid grid-cols-1 lg:grid-cols-6 gap-12">
          {/* Brand col */}
          <div className="lg:col-span-2">
            {/* Logo */}
            <Link href="/" className="flex items-center mb-5 w-fit">
              <Image
                src="/assets/images/logo/logo.png"
                alt="Nimble Software Lab"
                width={52}
                height={52}
                style={{
                  width: 52,
                  height: 52,
                  filter: 'brightness(0) invert(1)',
                }}
              />
            </Link>

            <p className="text-sm leading-relaxed mb-6" style={{ color: 'var(--text-2)', maxWidth: 280 }}>
              Enterprise-grade software engineering from Dhaka, Bangladesh. 40–60% less than US/UK agencies. Zero compromise.
            </p>

            {/* Contact info */}
            <div className="flex flex-col gap-3 mb-6">
              <span className="flex items-center gap-2.5 text-sm" style={{ color: 'var(--text-3)' }}>
                <Mail size={13} style={{ color: 'var(--blue-2)', flexShrink: 0 }} />
                info@nimblesl.com
              </span>
              <a href="tel:+8801796109979" className="flex items-center gap-2.5 text-sm hover:opacity-80 transition-opacity" style={{ color: 'var(--text-3)' }}>
                <Phone size={13} style={{ color: 'var(--blue-2)', flexShrink: 0 }} />
                +880-1796-109979
              </a>
              <div className="flex items-start gap-2.5 text-sm" style={{ color: 'var(--text-3)' }}>
                <MapPin size={13} style={{ color: 'var(--blue-2)', flexShrink: 0, marginTop: 2 }} />
                <span>House-1, Road-34, Gulshan-2<br />Dhaka-1212, Bangladesh</span>
              </div>
            </div>

            {/* Social links */}
            <div className="flex items-center gap-2">
              {[
                { icon: LinkedinIcon, href: 'https://www.linkedin.com/company/nimble-software-lab', label: 'LinkedIn' },
                { icon: FacebookIcon, href: 'https://www.facebook.com/nimblesl', label: 'Facebook' },
                { icon: GithubIcon, href: 'https://github.com', label: 'GitHub' },
              ].map(({ icon: Icon, href, label }) => (
                <a
                  key={label}
                  href={href}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={label}
                  className="w-8 h-8 rounded-lg flex items-center justify-center transition-all duration-150 hover:bg-white/10"
                  style={{ color: 'var(--text-3)', border: '1px solid var(--border)' }}
                >
                  <Icon size={14} />
                </a>
              ))}
            </div>
          </div>

          {/* Link columns */}
          {Object.entries(FOOTER_LINKS).map(([category, links]) => (
            <div key={category}>
              <h4 className="text-xs font-semibold uppercase tracking-widest mb-4"
                style={{ color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>
                {category}
              </h4>
              <ul className="flex flex-col gap-2.5">
                {links.map((link) => (
                  <li key={link.href}>
                    <Link
                      href={link.href}
                      className="text-sm transition-colors duration-150 hover:text-white"
                      style={{ color: 'var(--text-3)' }}
                    >
                      {link.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Tech stack strip */}
        <div className="mt-16 pt-8" style={{ borderTop: '1px solid var(--border)' }}>
          <div className="text-xs mb-4" style={{ color: 'var(--text-3)', fontFamily: 'var(--font-mono)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
            Technologies we ship with
          </div>
          <div className="flex flex-wrap gap-2">
            {TECH_BADGES.map((tech) => (
              <span key={tech} className="tag" style={{ fontSize: 11 }}>{tech}</span>
            ))}
          </div>
        </div>
      </div>

      {/* Bottom bar */}
      <div style={{ borderTop: '1px solid var(--border)' }}>
        <div className="container" style={{ padding: '20px 32px' }}>
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="text-xs" style={{ color: 'var(--text-3)' }}>
              © {new Date().getFullYear()} Nimble Software Lab. All rights reserved.
            </div>
            <div className="flex items-center gap-4">
              {/* Compliance badges */}
              {['GDPR', 'HIPAA', 'OWASP'].map((badge) => (
                <span key={badge} className="text-xs px-2 py-0.5 rounded"
                  style={{ color: 'var(--text-3)', border: '1px solid var(--border)', fontFamily: 'var(--font-mono)' }}>
                  {badge}
                </span>
              ))}
              <span className="text-xs" style={{ color: 'var(--text-3)' }}>
                Built with Next.js 15
              </span>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// src/app/layout/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

interface FooterLink {
  label: string;
  path: string;
  external?: boolean;
}

interface FooterSection {
  title: string;
  links: FooterLink[];
}

interface SocialLink {
  name: string;
  url: string;
  icon: string;
}

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {
  currentYear = new Date().getFullYear();

  footerSections: FooterSection[] = [
    {
      title: 'Services',
      links: [
        { label: 'Custom Software', path: '/services#custom-software' },
        { label: 'Web Applications', path: '/services#web-apps' },
        { label: 'Mobile Apps', path: '/services#mobile-apps' },
        { label: 'Cloud Solutions', path: '/services#cloud' },
        { label: 'AI Integration', path: '/services#ai' }
      ]
    },
    {
      title: 'Company',
      links: [
        { label: 'About Us', path: '/about' },
        { label: 'Case Studies', path: '/case-studies' },
        { label: 'Careers', path: '/careers' },
        { label: 'Contact', path: '/contact' }
      ]
    },
    {
      title: 'Resources',
      links: [
        { label: 'Blog', path: '/blog' },
        { label: 'Privacy Policy', path: '/privacy' },
        { label: 'Terms of Service', path: '/terms' }
      ]
    }
  ];

  socialLinks: SocialLink[] = [
    {
      name: 'LinkedIn',
      url: 'https://www.linkedin.com/company/nimblesl',
      icon: 'linkedin'
    },
    {
      name: 'GitHub',
      url: 'https://github.com/NimbleSL',
      icon: 'github'
    },
    {
      name: 'Facebook',
      url: 'https://www.facebook.com/nimblesl',
      icon: 'facebook'
    },
    {
      name: 'WhatsApp',
      url: 'https://wa.me/8801796109979',
      icon: 'whatsapp'
    }
  ];

  contactInfo = {
    email: 'hello@nimblesl.com',
    phone: '+880-1796-109979',
    address: 'Gulshan-2, Dhaka, Bangladesh'
  };
}

<footer class="footer">
  <div class="footer__container">
    <!-- Main Footer Content -->
    <div class="footer__main">
      <!-- Brand Column -->
      <div class="footer__brand">
        <a routerLink="/" class="footer__logo">
          <img src="assets/images/logo/logo.png" alt="Nimble Software Lab" class="footer__logo-img" />
        </a>
        <p class="footer__tagline">
          Building exceptional software for companies across the globe.
          Fast, nimble, and precise.
        </p>

        <!-- Social Links -->
        <div class="footer__social">
          @for (social of socialLinks; track social.name) {
          <a [href]="social.url" target="_blank" rel="noopener noreferrer" class="footer__social-link"
            [attr.aria-label]="social.name">
            <!-- SVG Icons -->
            @switch (social.icon) {
            @case ('linkedin') {
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path
                d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
            </svg>
            }
            @case ('github') {
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path
                d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
            </svg>
            }
            @case ('twitter') {
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path
                d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
            </svg>
            }
            }
          </a>
          }
        </div>
      </div>

      <!-- Navigation Columns -->
      @for (section of footerSections; track section.title) {
      <div class="footer__column">
        <h4 class="footer__column-title">{{ section.title }}</h4>
        <ul class="footer__links">
          @for (link of section.links; track link.path) {
          <li>
            <a [routerLink]="link.path" class="footer__link">
              {{ link.label }}
            </a>
          </li>
          }
        </ul>
      </div>
      }

      <!-- Contact Column -->
      <div class="footer__column footer__contact">
        <h4 class="footer__column-title">Get in Touch</h4>
        <div class="footer__contact-info">
          <a href="mailto:{{ contactInfo.email }}" class="footer__contact-item">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
              <polyline points="22,6 12,13 2,6" />
            </svg>
            {{ contactInfo.email }}
          </a>
          <a href="tel:{{ contactInfo.phone }}" class="footer__contact-item">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path
                d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
            </svg>
            {{ contactInfo.phone }}
          </a>
          <div class="footer__contact-item">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
              <circle cx="12" cy="10" r="3" />
            </svg>
            {{ contactInfo.address }}
          </div>
        </div>
      </div>
    </div>

    <!-- Footer Bottom -->
    <div class="footer__bottom">
      <p class="footer__copyright">
        © {{ currentYear }} Nimble Software Lab. All rights reserved.
      </p>
      <div class="footer__bottom-links">
        <a routerLink="/privacy" class="footer__bottom-link">Privacy</a>
        <a routerLink="/terms" class="footer__bottom-link">Terms</a>
      </div>
    </div>
  </div>
</footer>
